<?= $this->inlineScript()
    ->prependFile($this->basePath('js/projetogeral/validacaoAuth.js'))
?>

<div class="container-fluid">
	<div class="row">
		<div class="col-5 bg-blue center">
			<div>
				<h1 class="h1-fornecedor">Portal do<br> fornecedor</h1>

				<img class="w-100 mg-top img"
					 src="/img/shibata-supermercados.svg"
					 alt="Shibata Supermercados" title="Shibata Supermercados">
			</div>
		</div>

		<div class="col-7 center">
			<form class="form-control-login" method="post">
				<div>
					<h1 class="h1-login">Seja bem-vindo</h1>

					<p class="mt-5 p-login">FAÇA SEU LOGIN</p>
				</div>
				<div class="form-floating mt-4 m-3 ">
					<input type="username" name="username" id="username" class="form-control login-center-usuario"
						   placeholder="name">
					<label class="login-center-label-usuario">usuário</label>
				</div>
				<div class="form-floating m-3">
					<input type="password" id="password" name="password" class="form-control login-center-pass"
						   placeholder="Senha">
					<label class="login-center-label-pass">Senha</label>
				</div>

				<div class="text-center">
					<button type="button" class="btn-lg btn-danger" id="btnEntrar">
						<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
							 class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
							<path fill-rule="evenodd"
								  d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"></path>
							<path fill-rule="evenodd"
								  d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"></path>
						</svg>
						Entrar
					</button>
				</div>

				<div class="text-center">
					<p class="text-muted p-novoUsuario">Ainda não tem conta? <a class="w-65 mt-3 login-a"
																				id="btnNovoCadastro" type="button"
																				href="portal/cadastro">
							Cadastre-se
						</a></p>
				</div>

<!--				<div class="text-center">-->
<!--					<label>-->
<!--						<a class="login-a" href="">Esqueceu a senha?</a>-->
<!--					</label>-->
<!--				</div>-->
			</form>
		</div>
	</div>
</div>

