<footer class="bg-blue" id="footer">
	<div class="container my-auto">
		<div class="text-light sticky-footer">
			<div class="copyright text-center my-auto">
<!--				<span>&copy; <strong>Shibata Supermercados</strong> --><?//= date('Y'); ?><!--</span>-->

				<strong>Copyright &copy;<a class="text-light text-decoration-none" href="https://shibata.com.br/"> Shibata Supermercados - </a> <?= Date('Y') ?></strong>
			</div>
		</div>
	</div>
</footer>

