
<!--<section>-->
<!--	<div class="container">-->
<!--		<div class="rows">-->
<!--			<div class="col-sm-12 col-md-8 col-lg-9 ms-sm-auto">-->
<!--				<div class="table_responsive">-->
<!--					<table id="tablePortal" class="table table-striped table-sm">-->
<!--						<thead>-->
<!--						<tr>-->
<!--							<th scope="col">EAN</th>-->
<!--							<th scope="col">Rereferência</th>-->
<!--							<th scope="col">Descrição</th>-->
<!--							<th scope="col">Tipo De Embalagem</th>-->
<!--							<th scope="col">Unidade</th>-->
<!--							<th scope="col">Qtd Por Embalagem</th>-->
<!--							<th scope="col">Valor Un.</th>-->
<!--							<th scope="col">Valor Total</th>-->
<!--						</tr>-->
<!--						</thead>-->
<!--					</table>-->
<!--				</div>-->
<!--			</div>-->
<!---->
<!--			<div class="col-sm-12 col-md-4 col-lg-3">-->
<!--				<div class="text-center mt-5 my-auto">-->
<!--					<h5>Complete com os valores ou <br> escolha alguma opção abaixo</h5>-->
<!--				</div>-->
<!--				<div class="bg-light border  rounded mt-5 h-100 d-flex justify-content-center align-items-center">-->
<!--					<div class="p-3 d-flex justify-content-center">-->
<!--						<div class="col-12 col-sm-12 col-md-12 col-lg-12">-->
<!--							<button id="btnExportar" type="button" class="btnExportar btn btn-primary rounded p-2 col-12 col-sm-12 col-md-12 col-lg-12">-->
<!--								<div class="text-light text-center">-->
<!--									<svg xmlns="http://www.w3.org/2000/svg" width="40" height="50" fill="currentColor"-->
<!--										 class="bi bi-cloud-arrow-down-fill" viewBox="0 0 16 16">-->
<!--										<path d="M8 2a5.53 5.53 0 0 0-3.594 1.342c-.766.66-1.321 1.52-1.464 2.383C1.266 6.095 0 7.555 0 9.318 0 11.366 1.708 13 3.781 13h8.906C14.502 13 16 11.57 16 9.773c0-1.636-1.242-2.969-2.834-3.194C12.923 3.999 10.69 2 8 2zm2.354 6.854-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 1 1 .708-.708L7.5 9.293V5.5a.5.5 0 0 1 1 0v3.793l1.146-1.147a.5.5 0 0 1 .708.708z"></path>-->
<!--									</svg>-->
<!--									<br>-->
<!--									Exportar tabela para preenchimento-->
<!--								</div>-->
<!--							</button>-->
<!---->
<!--							<button id="btnCarregar" type="button" class="btnCarregar btn btn-primary rounded mt-3 p-2 col-12 col-sm-12 col-md-12 col-lg-12">-->
<!--								<div class="text-light text-center">-->
<!--									<svg xmlns="http://www.w3.org/2000/svg" width="40" height="50" fill="currentColor"-->
<!--										 class="bi bi-cloud-download-fill" viewBox="0 0 16 16">-->
<!--										<path fill-rule="evenodd"-->
<!--											  d="M8 0a5.53 5.53 0 0 0-3.594 1.342c-.766.66-1.321 1.52-1.464 2.383C1.266 4.095 0 5.555 0 7.318 0 9.366 1.708 11 3.781 11H7.5V5.5a.5.5 0 0 1 1 0V11h4.188C14.502 11 16 9.57 16 7.773c0-1.636-1.242-2.969-2.834-3.194C12.923 1.999 10.69 0 8 0zm-.354 15.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 14.293V11h-1v3.293l-2.146-2.147a.5.5 0 0 0-.708.708l3 3z"></path>-->
<!--									</svg>-->
<!--									<br>-->
<!--									Carregar arquivo já preenchido-->
<!--								</div>-->
<!--							</button>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
<!---->
<!--			<div class="mt-5 col-sm-12 col-md-4 col-lg-3">-->
<!--				<div class="h-100 d-flex justify-content-center align-items-center">-->
<!--					<div class="p-3 d-flex justify-content-center">-->
<!--						<div class="col-12 col-sm-12 col-md-12 col-lg-12">-->
<!--							<button id="btnSalvar" type="button" class="btnSalvar btn btn-danger btn-lg p-4">-->
<!--								<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-save" viewBox="0 0 16 16" height="20" width="40">-->
<!--									<path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H9.5a1 1 0 0 0-1 1v7.293l2.646-2.647a.5.5 0 0 1 .708.708l-3.5 3.5a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L7.5 9.293V2a2 2 0 0 1 2-2H14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h2.5a.5.5 0 0 1 0 1H2z"></path>-->
<!--								</svg>-->
<!---->
<!--								SALVAR E CONTINUAR-->
<!--							</button>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->
<!--</section>-->
