<?php $this->inlineScript()
    ->prependFile($this->basePath('js/projetogeral/agendamentovisita.js'))
?>

<style>

    h6 {
        font-size: 18px;
    }

    h1, h2, h3, h4, h5, h6 {
        color: #1F3463;
    }

    .primary-button {
        background-color: #AD272D;
        color: ;
        --bs-bg-opacity: 1;
    }

    .primary-button:hover {
        background-color: #D24248;
        color: ;
        --bs-bg-opacity: 1;
    }

    .border-primary {
        border-color: #3253A1 !important;
    }

    .bg-card-visita {
        background-color: #3253A1;
    }

    .card-body-background {
        background: #E9F2F8;
    }

    a {
        -webkit-transition: .3s all ease;
        -o-transition: .3s all ease;
        transition: .3s all ease;
    }

    a, a:hover {
        text-decoration: none !important;
    }


    h2 {
        font-size: 20px;
    }

    .horario:hover {
        display: block;
        background-color: red;
        border-radius: 10px;
        color: white;
    }

    .form-control:active, .form-control:focus {
        outline: none;
        -webkit-box-shadow: none;
        box-shadow: none;
    }
</style>

<main>
	<section>
		<div class="container">
			<div id="cadastro" class="row gx-4 gx-lg-5">
				<div class="col-6 col-sm-6 col-md-6 col-lg-3 col-xl--3 ">
					<div class="mt-4 rounded border border-primary">
						<div class="rounded">
							<h6 class="representante text-center m-3 pt-2">1. Cadastro do Representante</h6>
						</div>
					</div>
				</div>

				<div class="col-6 col-sm-6 col-md-6 col-lg-3 col-xl--3 ">
					<div class="mt-4 rounded border border-primary">
						<div class="rounded disabled">
							<h6 class="text-center m-3 pt-2">2. Solicitação de Visita</h6>
						</div>
					</div>
				</div>

				<div class="col-6 col-sm-6 col-md-6 col-lg-3 col-xl--3 ">
					<div class="mt-4 rounded border border-primary">
						<div class="rounded disabled">
							<h6 class="text-center m-3 pt-2">3. Confirmação</h6>
						</div>
					</div>
				</div>

				<div id="salvarContinuar" class="col-6 col-sm-6 col-md-6 col-lg-3 col-xl-3">
					<div class="card mt-4">
						<button class="primary-button rounded" type="button" id="btnVisita">
							<h6 class="text-light text-center m-3 pt-2">Salvar e continuar</h6>
						</button>
					</div>
				</div>
			</div>

			<div disabled="none" class="main-container row gx-4 gx-lg-5">
				<div class="col-12 col-sm-12 col-md-12 col-lg-5" id="informacoes">
					<div class="h-100">
						<div class="card-body">
							<h3 class="p-3 card-title">Informações</h3>
							<div class="text-center row mb-2">
								<div class="col-12 col-md-6">
									<p class="card-text text-muted">Nome da empresa</p>
									<h5 class="card-title" name="razao_social" id="razao_social" disabled=""></h5>
								</div>

								<div class="col-12 col-md-6">
									<p class="card-text text-muted">Nome do Representante</p>
									<h5 class="card-title" name="nome_completo" id="nome_completo"></h5>
								</div>
							</div>

							<div class="text-center row mb-2">
								<div class="col-md-6">
									<p class="card-text text-muted">CPF</p>
									<h5 class="card-title" name="doc1" id="doc1"></h5>
								</div>

								<input type="hidden" class="form-control" id="representante_id"
									   name="representante_id"/>

								<div class="col-md-6">
									<p class="card-text text-muted">Frequência da Visita</p>
									<h5 class="card-title" name="frequencia_visita" id="frequencia_visita">Regular</h5>
								</div>
							</div>

							<div class="text-center row mb-2">
								<div class="col-md-6">
									<p class="card-text text-muted">Linha dos produtos</p>
									<h5 class="card-title" name="linha_produtos" id="linha_produtos">FLV</h5>
								</div>

								<div class="col-md-6">
									<p class="card-text text-muted">Contato comercial</p>
									<h5 class="card-title" name="contato" id="contato"></h5>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-12 col-sm-12 col-md-12 col-lg-7" id="uploadVisita">
					<div class="card h-100">
						<div class="d-flex align-items-center justify-content-center card-body card-body-background">
							<div class="text-center row">
								<div class="col-md-6 d-flex justify-content-around align-items-end" style="">
									<h6 class="card-title">Carregue seus documentos:</h6>
								</div>

								<div class="col-md-6">


									<div class="btnModalFoto">
										<button type="button"
												class="rounded mt-4 rounded border bg-card-visita col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12"
												data-toggle="modal" data-target="#modalShowFoto">
											<div class="text-light text-center m-3 pt-2" for="selecao-arquivo">
												<!--												<input class="form-check-input" type="checkbox" id="myCheckBox"-->
												<!--													   disabled="disabled"/>-->
												<svg xmlns="http://www.w3.org/2000/svg" width="40" height="16"
													 fill="currentColor" class="bi bi-card-heading" viewBox="0 0 16 16">
													<path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"></path>
													<path d="M3 8.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm0-5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5v-1z"></path>
												</svg>
												Demais Doc
											</div>
										</button>
									</div>

<!--									<div class="btnModalCartao">-->
<!--										<button type="button"-->
<!--												class="rounded mt-4 rounded border bg-card-visita col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12"-->
<!--												data-toggle="modal" data-target="#modalShowCartao">-->
<!--											<div class="text-light text-center m-3 pt-2" for="selecao-arquivo">-->
<!--												<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"-->
<!--													 fill="currentColor" class="bi bi-person-badge-fill"-->
<!--													 viewBox="0 0 16 16">-->
<!--													<path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm4.5 0a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1h-3zM8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm5 2.755C12.146 12.825 10.623 12 8 12s-4.146.826-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"></path>-->
<!--												</svg>-->
<!--												Cartão-->
<!--												de visita-->
<!--											</div>-->
<!--										</button>-->
<!--									</div>-->
<!---->
<!--									<div class="btnModalDoc">-->
<!--										<button type="button"-->
<!--												class="modalShow rounded mt-4 rounded border bg-card-visita col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12"-->
<!--												data-toggle="modal" id="demaisDoc" data-target="#modalShoDoc">-->
<!--											<div class="text-light text-center m-3 pt-2" for="selecao-arquivo">-->
<!---->
<!--												<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"-->
<!--													 fill="currentColor" class="bi bi-file-earmark-medical"-->
<!--													 viewBox="0 0 16 16">-->
<!--													<path d="M7.5 5.5a.5.5 0 0 0-1 0v.634l-.549-.317a.5.5 0 1 0-.5.866L6 7l-.549.317a.5.5 0 1 0 .5.866l.549-.317V8.5a.5.5 0 1 0 1 0v-.634l.549.317a.5.5 0 1 0 .5-.866L8 7l.549-.317a.5.5 0 1 0-.5-.866l-.549.317V5.5zm-2 4.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zm0 2a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"></path>-->
<!--													<path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"></path>-->
<!--												</svg>-->
<!--												Demais Doc-->
<!---->
<!--											</div>-->
<!--										</button>-->
<!--									</div>-->
								</div>
							</div>

							<div class="modal fade" id="modalShowFoto" tabindex="-1"
								 aria-hidden="true">
								<div class="modal-dialog modal-lg">
									<div class="modal-content">
										<div class="modal-content">

											<div class="modal-header">
												<h5 class="modal-title">Enviar
													Arquivo</h5>
												<button type="button" class="close" data-dismiss="modal"
														aria-label="Close">
												</button>
											</div>
											<div class="modal-body">
												<form id="uploadFoto" name="uploadForm" method="post"
													  enctype="multipart/form-data">
													<input id="fileFoto" type="file" name="file">
												</form>
											</div>

											<div class="modal-footer">
												<button type="button" id="btnHideFoto" class="btn btn-danger"
														data-dismiss="modal">Fechar
												</button>
												<button type="button" id="btnUploadFoto" class="btn btn-primary">
													Salvar
												</button>
											</div>
										</div>
									</div>
								</div>
							</div>

<!--							<div class="modal fade" id="modalShowCartao" tabindex="-1"-->
<!--								 aria-labelledby="exampleModalLabel" aria-hidden="true">-->
<!--								<div class="modal-dialog modal-lg">-->
<!--									<div class="modal-content">-->
<!--										<div class="modal-content">-->
<!---->
<!--											<div class="modal-header">-->
<!--												<h5 class="modal-title">Enviar-->
<!--													Arquivo</h5>-->
<!--												<button type="button" class="close" data-dismiss="modal"-->
<!--														aria-label="Close">-->
<!--												</button>-->
<!--											</div>-->
<!--											<div class="modal-body">-->
<!--												<form id="uploadCartao" name="uploadForm" method="post"-->
<!--													  enctype="multipart/form-data">-->
<!--													<input id="fileCartao" type="file" name="file">-->
<!---->
<!--												</form>-->
<!--											</div>-->
<!---->
<!--											<div class="modal-footer">-->
<!--												<button type="button" id="btnHideCartao" class="btn btn-danger"-->
<!--														data-dismiss="modal">Fechar-->
<!--												</button>-->
<!--												<button type="button" id="btnUploadCartao" class="btn btn-primary">-->
<!--													Salvar-->
<!--												</button>-->
<!--											</div>-->
<!--										</div>-->
<!--									</div>-->
<!--								</div>-->
<!--							</div>-->
<!---->
<!--							<div class="modal fade" id="modalShowDoc" tabindex="-1" aria-labelledby="exampleModalLabel"-->
<!--								 aria-hidden="true">-->
<!--								<div class="modal-dialog modal-lg">-->
<!--									<div class="modal-content">-->
<!--										<div class="modal-content">-->
<!---->
<!--											<div class="modal-header">-->
<!--												<h5 class="modal-title">Enviar-->
<!--													Arquivo</h5>-->
<!--												<button type="button" class="close" data-dismiss="modal"-->
<!--														aria-label="Close">-->
<!--												</button>-->
<!--											</div>-->
<!--											<div class="modal-body">-->
<!--												<form id="uploadDoc" name="uploadForm" method="post"-->
<!--													  enctype="multipart/form-data">-->
<!---->
<!--													<input id="fileDoc" type="file" name="fileDoc">-->
<!--												</form>-->
<!--											</div>-->
<!---->
<!--											<div class="modal-footer">-->
<!--												<button type="button" id="btnHideDoc" class="btn btn-danger"-->
<!--														data-dismiss="modal">Fechar-->
<!--												</button>-->
<!--												<button type="button" id="btnUploadDoc" class="btn btn-primary">-->
<!--													Salvar-->
<!--												</button>-->
<!--											</div>-->
<!--										</div>-->
<!--									</div>-->
<!--								</div>-->
<!--							</div>-->
						</div>
					</div>
				</div>

				<div style="display: none" class="col-12 col-sm-12 col-md-12 col-lg-7" id="data">
					<div class="card">
						<div class="card-body card-body-background">
							<h3 class="p-3 card-title">Selecione uma Data</h3>
							<div id="inline_cal" data-rome-id="0">
								<input type="hidden" class="form-control data_agendamento_class" id="data_agendamento"
									   name="data_agendamento"/>
							</div>
						</div>
					</div>
				</div>

				<div style="display: none" class="col-12 col-sm-12 col-md-12 col-lg-7" id="horario">
					<div class="card">
						<h3 class="p-3 ">Selecione um Horario</h3>
						<div class="row p-4 text-center">
							<div class="col-4 p-2 horario">08:00 - 09:00</div>
							<div class="col-4 p-2 horario">09:00 - 10:00</div>
							<div class="col-4 p-2 horario">10:00 - 11:00</div>
						</div>

						<div class="row p-4 text-center">
							<div class="col-4 p-2 horario" style="display: block;">11:00 - 12:00</div>
							<div class="col-4 p-2 horario" style="display: block;">12:00 - 13:00</div>
							<div class="col-4 p-2 horario" style="display: block;">13:00 - 14:00</div>
						</div>

						<div class="row p-4 text-center">
							<div class="col-4 p-2 horario" style="display: block;">14:00 - 15:00</div>
							<div class="col-4 p-2 horario" style="display: block;">15:00 - 16:00</div>
							<div class="col-4 p-2 horario" style="display: block;">16:00 - 17:00</div>
						</div>

						<div class="row p-4 text-center">
							<div class="col-4 p-2 horario" style="display: block;">17:00 - 18:00</div>
						</div>
					</div>
				</div>

				<div style="display: none" class="col-12 col-sm-12 col-md-12 col-lg-12" id="confirmacaoVisita">
					<h1 id="confirmeInformacao" class="text-center">Confirme as informações</h1>
					<h1 style="display: none" id="confirmeCadastro" class="text-center text-success">
						<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor"
							 class="bi bi-check-square-fill" viewBox="0 0 16 16">
							<path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm10.03 4.97a.75.75 0 0 1 .011 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.75.75 0 0 1 1.08-.022z"/>
						</svg>
						Solicitação cadastrada com sucesso
					</h1>

					<div class="text-center row mt-5">
						<div class="col-6 col-md-3">
							<h6 class="card-text text-muted">Empresa</h6>
							<h5 class="card-title" name="razao_social_agendamento" id="razao_social_agendamento"
								disabled=""></h5>
						</div>

						<div class="col-6 col-md-3">
							<h6 class="card-text text-muted">Representante</h6>
							<h5 class="card-title" name="nome_completo_agendamento" id="nome_completo_agendamento"></h5>
						</div>

						<div class="col-6 col-md-3">
							<h6 class="card-text text-muted">Dia da visita</h6>
							<h5 class="card-title" name="agendamento_data" id="agendamento_data"></h5>
						</div>

						<div class="col-6 col-md-3">
							<h6 class="card-text text-muted">Horário</h6>
							<h5 class="card-title" name="horario_agendamento" id="horario_agendamento"></h5>
						</div>
					</div>

					<div class="form-row text-center">
						<div class="col-12 mt-5">
							<p>
								<a class="btn btn-danger btn-lg" role="button" id="btnAgendamento">
									<svg xmlns="http://www.w3.org/2000/svg" width="30" height="20" fill="white"
										 class="bi bi-calendar2-check" viewBox="0 0 16 16">
										<path d="M10.854 8.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L7.5 10.793l2.646-2.647a.5.5 0 0 1 .708 0z"></path>
										<path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM2 2a1 1 0 0 0-1 1v11a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H2z"></path>
										<path d="M2.5 4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5V4z"></path>
									</svg>
									Agendar
								</a>
							</p>
						</div>
					</div>

					<div class="form-row text-center">
						<div class="col-12 mt-5">
							<p>
								<a style="display:none;" class="btn btn-primary btn-lg" href="/portal/" role="button"
								   id="btnConfirmacaoAgendamento">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
										 class="bi bi-arrow-left" viewBox="0 0 16 16">
										<path fill-rule="evenodd"
											  d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"></path>
									</svg>
									Voltar para Home
								</a>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>


</main>
