<?php $this->inlineScript()
    ->prependFile($this->basePath('js/projetogeral/cadastro.js'))
?>

<main>
	<section class="bg-blue">
		<div id="registerHidden" class="container  center-main">
			<div class="row">
				<div class="p-4 card-body">
					<div id="addClass" style="display: none">
						<h4 class="card-title text">Empresa</h4>
					</div>
					<div>
						<h5 class="text-center text removeClassCnpj" id="infoCnpj">Informe o CNPJ de sua
							empresa</h5>
						<div class="pesquisar input-group ">
							<div class="mb-3">
								<input type="text" class="form-control " name="cnpj" id="cnpj" placeholder="CNPJ"
									   required="required" pattern="\d*"/>
							</div>

							<div class="text-center mt-4">
								<button type="button" id="btnFilter"
										class=" w-100 btn btn-danger removeClassCnpj">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
										 fill="currentColor"
										 class="bi bi-search" viewBox="0 0 16 16">
										<path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
									</svg>
									Pesquisar
								</button>
							</div>
						</div>
					</div>
					<form id="FormCadastro">
						<div class="removeClass" id="displayForm" style="display: none">
							<div class="row mb-2">
								<div class="col-md-6 mb-2">
									<input type="text" class="form-control" placeholder="Razão Social"
										   id="razao_social"
										   name="razao_social"/>
								</div>

								<div class="col-md-6 mb-2">
									<input type="text" class="form-control" id="nome_fantasia"
										   placeholder="Nome Fantasia"
										   name="nome_fantasia">
								</div>
							</div>

							<div class="row mb-2">
<!--								<div class="col-4 col-sm-3 col-md-2 col-lg-2 col-xl-2 mb-2">-->
<!--									<input type="text" class="form-control" placeholder="DDD"-->
<!--										   id="empresa_ddd_celular"-->
<!--										   name="ddd_celular" pattern="\d*"/>-->
<!--								</div>-->
<!---->
<!--								<div class="col-8 col-sm-9 col-md-4 col-lg-4 col-xl-4 mb-2">-->
<!--									<input type="text" class="form-control" placeholder="Celular" id="empresa_celular"-->
<!--										   name="celular" pattern="\d*"/>-->
<!--								</div>-->

								<div class="col-4 col-sm-3 col-md-2 col-lg-2 col-xl-2 mb-2">
									<input type="text" class="form-control" maxlength="2" size="2" placeholder="DDD"
										   id="empresa_ddd_telefone"
										   name="ddd_telefone" pattern="\d*"/>
								</div>

								<div class="col-8 col-sm-9 col-md-4 col-lg-4 col-xl-4 mb-2">
									<input type="text" class="form-control" placeholder="Telefone" id="empresa_telefone"
										   name="telefone" pattern="\d*"/>
								</div>

								<h4 class="card-title text">Endereço</h4>

								<div class="row mb-2">
									<div class="col-6 col-md-3 mb-2">
										<input type="text" class="form-control" placeholder="CEP" id="cep"
											   name="cep" required="required" pattern="\d*">
									</div>

									<div class="col-6 col-md-4 mb-2">
										<button type="button" class="btn btn-danger" id="btnPesquisarCep">
											<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
												 fill="currentColor"
												 class="bi bi-search" viewBox="0 0 16 16">
												<path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
											</svg>
										</button>
									</div>
								</div>

								<div class="row mb-2">
									<div class="col-12 col-md-5 mb-2">
										<input type="text" class="form-control" placeholder="Rua" name="rua" id="rua"
											   disabled>
									</div>

									<div class="col-4 col-md-2 mb-2">
										<input type="text" class="form-control" placeholder="Nº" name="numero"
											   id="numero"
											   pattern="[0-9]+$" disabled>
									</div>

									<div class="col-8 col-md-5 mb-2">
										<input type="text" class="form-control" placeholder="Complemento"
											   id="complemento" name="complemento" disabled>
									</div>
								</div>

								<div class="row mb-2">
									<div class="col-md-6 mb-2">
										<input type="text" class="form-control" placeholder="Bairro" id="bairro"
											   name="bairro"
											   disabled>
									</div>

									<div class="col-md-6 mb-2">
										<input type="text" class="form-control" placeholder="Município" id="municipio"
											   name="municipio" disabled>
									</div>
								</div>

								<div class="row mb-2">
									<div class="col-md-6 mb-2">
										<input type="text" class="form-control " placeholder="Estado" id="estado"
											   name="estado"
											   disabled>
									</div>

									<div class="col-md-6 mb-2">
										<input type="text" class="form-control tex" placeholder="Cidade" id="cidade"
											   name="cidade" disabled>
									</div>
								</div>

								<div class="row mb-2 text-center">
									<div class="mb-2">
										<button type="button" id="btnCadastrarEmpresa" class="btn btn-danger ">
											<svg xmlns="http://www.w3.org/2000/svg" width="16" height="22"
												 fill="currentColor"
												 class="bi bi-building" viewBox="0 0 16 16">
												<path fill-rule="evenodd"
													  d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022zM6 8.694 1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z"></path>
												<path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 0h1v1h-1V5zm0-2h1v1h-1V3z"></path>
											</svg>
											Cadastrar
										</button>

										<button type="button" class="btn btn-primary">
											<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
												 fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
												<path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
											</svg>
											<a class="text-light" href="/"></a>Home
										</button>
									</div>
								</div>
							</div>
						</div>
					</form>


					<form id="FormCadastroUsuario" style="display: none">
						<div>
							<h4 class="card-title text">Dados do Representante</h4>
						</div>
						<div class="row mb-2">
							<div class="col-md-6 mb-2">
								<input type="text" class="form-control" placeholder="CPF" id="doc1" name="doc1"
									   required="required" pattern="\d*"/>
							</div>

							<div class="col-md-6 mb-2">
								<select name="representante_tipo_id" id="representante_tipo_id" class="form-control" aria-label="Default select">
									<option disabled selected>Selecione o seu cargo</option>
									<option value="1">Representante</option>
									<option value="2">Gerente</option>
									<option value="3">Supervisor</option>
									<option value="4">Coordenador</option>
									<option value="5">Vendedor</option>
									<option value="6">Produtor</option>
								</select>
							</div>

							<input type="hidden" class="form-control" id="empresa_id" name="empresa_id"/>
							<input type="hidden" class="form-control" id="id_representante" name="id_representante"/>
							<input type="hidden" class="form-control" id="id_endereco" name="id_endereco"/>
						</div>

						<div class="row mb-2">
							<div class="col-12 col-sm-2 col-md-3 col-lg-2 col-xl-2 mb-2 text-center">
								<h6 for="exampleFormControlTextarea1" class="card-title text form-label">Frequência de visitas</h6>
								<input type="text" id="frequencia" name="frequencia" class="form-control text-center" maxlength="4" size="4" placeholder="Dias Frenq.">
							</div>
						</div>

						<div class="row mb-2">
							<div class="col-md-6 mb-2">
								<input type="text" class="form-control " placeholder="Nome Completo" id="nome_completo"
									   name="nome_completo"
								/>
							</div>

							<div class="col-md-6 mb-2">
								<input type="email" class="form-control" placeholder="E-mail" id="email" name="email">
							</div>
						</div>

						<div class="row mb-2">
							<div class="col-4 col-sm-3 col-md-2 col-lg-2 col-xl-2 mb-2">
								<input type="text" class="form-control" placeholder="DDD"
									   id="usuario_ddd_celular"
									   name="ddd_celular" pattern="\d*"/>
							</div>

							<div class="col-8 col-sm-9 col-md-4 col-lg-4 col-xl-4 mb-2">
								<input type="text" class="form-control" placeholder="Celular" id="usuario_celular"
									   name="celular" pattern="\d*"/>
							</div>

							<div class="col-4 col-sm-3 col-md-2 col-lg-2 col-xl-2 mb-2">
								<input type="text" class="form-control" maxlength="2" size="2" placeholder="DDD"
									   id="usuario_ddd_telefone"
									   name="ddd_telefone" pattern="\d*"/>
							</div>

							<div class="col-8 col-sm-9 col-md-4 col-lg-4 col-xl-4 mb-2">
								<input type="text" class="form-control" placeholder="Telefone" id="usuario_telefone"
									   name="telefone" pattern="\d*"/>
							</div>
						</div>

						<div class="row mb-2 text-center">
							<div class="mb-2">
								<button type="button" id="btnNovoUsuario" class="btn btn-danger" href="/">
									<svg xmlns="http://www.w3.org/2000/svg" width="25" height="22" fill="currentColor"
										 class="bi bi-person-plus-fill" viewBox="0 0 16 16">
										<path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
										<path fill-rule="evenodd"
											  d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"
										/>
									</svg>
									Cadastrar
								</button>

								<button type="button" class="btn btn-primary">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
										 class="bi bi-house-door-fill" viewBox="0 0 16 16">
										<path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
									</svg>
									<a class="text-light" href="/"></a>Home
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>

		<div style="display: none" id="infoLogin" class="content">
			<div class="container">
				<h2 class="my-5 text-center text-light">
					<svg xmlns="http://www.w3.org/2000/svg" width="50" height="30" fill="currentColor"
						 class="bi bi-bookmark-check" viewBox="0 0 16 16">
						<path fill-rule="evenodd"
							  d="M10.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"></path>
						<path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"></path>
					</svg>
					Cadastro realizado com sucesso
				</h2>

			</div>
			<div class="container">
				<div class="custom-accordion Larger shadow" id="accordion_1">
					<div class="accordion-item Larger shadow active">
						<h2 class="mb-0 text-decoration-none">
							<button class="btn btn-link text-decoration-none text-black" type="button" data-toggle="collapse"
									data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Informações sobre o registro
							</button>
						</h2>
						<div id="collapseOne" class="collapse show text-decoration-none" aria-labelledby="headingOne"
							 data-parent="#accordion_1">
							<div class="accordion-body">
								O seu registro passara por uma avaliação, estando tudo certo, você receber um E-mail com
								o seu login e senha para ter acesso ao nosso portal.
							</div>
						</div>
					</div>
				</div>

				<button href="/" type="button" class="btn btn-primary Small shadow m-4">
					<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
						 class="bi bi-house-door-fill" viewBox="0 0 16 16">
						<path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"></path>
					</svg>
					<a href="/" class="text-light">Home</a>
				</button>
			</div>
		</div>
	</section>
	<main>




