<?= $this->doctype() ?>

<html lang="pt-br">
<head>
    <?= $this->headTitle('Portal :: Shibata Supermercados'); ?>

    <?= $this->headMeta()->setCharset('utf-8'); ?>

    <?php $this->headMeta()
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendHttpEquiv('expires', 'Wed, 26 Feb 1997 08:21:57 GMT')
        ->appendHttpEquiv('pragma', 'no-cache')
        ->appendHttpEquiv('Cache-Control', 'no-cache');
    ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('description', 'Shibata Supermercados')
        ->appendName('author', 'Shibata Supermercados')
        ->appendName('keywords', 'Shibata,Supermercados');
    ?>


	<!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'href' => '/img/favicon.png'], 'PREPEND')
        /**
         * Style
         */
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/spinner/jquery.spinner.min.css'))
        ->prependStylesheet($this->basePath('css/rome/rome.css'))
        ->prependStylesheet($this->basePath('css/upload/uploadfilemulti.css'))
        ->prependStylesheet($this->basePath('css/datatable/Buttons/css/buttons.dataTables.css'))
        ->prependStylesheet($this->basePath('css/datatable/dataTables.css'))
        ->prependStylesheet($this->basePath('css/datepicker/bootstrap-datepicker.min.css'))
    ?>
	<!-- Scripts -->
    <?php $this->headScript() ?>

</head>

<body id="page-top">

<?= $this->content; ?>

<?= $this->inlineScript()
    ->prependFile($this->basePath('js/projetogeral/Request.js'))
    ->prependFile($this->basePath('js/spinner/jquery.spinner.min.js'))
    ->prependFile($this->basePath('js/jQueryMask/src/jquery.mask.js'))
    ->prependFile($this->basePath('js/bootbox/bootbox.locales.js'))
    ->prependFile($this->basePath('js/bootbox/bootbox.js'))
    ->prependFile($this->basePath('js/rome/rome.js'))
    ->prependFile($this->basePath('js/upload/jquery.fileuploadmulti.min.js'))
    ->prependFile($this->basePath('js/bootbox/bootbox.all.js'))
    ->prependFile($this->basePath('js/datatable/Buttons/js/pdfmake.min.js'))
    ->prependFile($this->basePath('js/datatable/Buttons/js/jszip.min.js'))
    ->prependFile($this->basePath('js/datatable/Buttons/js/vfs_fonts.js'))
    ->prependFile($this->basePath('js/datatable/Buttons/js/buttons.html5.js'))
    ->prependFile($this->basePath('js/datatable/Buttons/js/dataTables.buttons.js'))
    ->prependFile($this->basePath('js/datatable/Buttons/js/buttons.print.js'))
    ->prependFile($this->basePath('js/datatable/datatables.js'))
    ->prependFile($this->basePath('js/bootstrap/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery/jquery-3.6.0.min.js'))
//    ->prependFile($this->basePath('js/jquery/jquery-3.5.1.min.js'))
?>
</body>
</html>
