<?php $this->inlineScript()
    ->prependFile($this->basePath('js/projetogeral/editaragendamento.js'))
?>

<section class=" container pt-4">
	<div class="row gx-4 gx-lg-5">
		<div class="col-md-12 my-auto mb-5">
			<div class="h-100">
				<table id="table" class="table table-hover text-center mt-2 w-100 collapsing">
					<h2 class="card-title text-center">Meus agendamentos</h2>

					<thead class="thead-light bg-danger">
					<tr class="mt-4">
						<th class="text-light text-center align-middle nowrap">#</th>
						<th class="text-light text-center align-middle nowrap">Representante</th>
						<th class="text-light text-center align-middle nowrap">Data</th>
						<th class="text-light text-center align-middle nowrap">Hora</th>
						<th class="text-light text-center align-middle nowrap">Agendamentos</th>
					</tr>
					</thead>
				</table>
			</div>
		</div>
	</div>
</section>

