<?php $this->headLink()
    ->prependStylesheet($this->basePath('css/404.css'));
?>

<style>
    body {
        background-color: white;
    }
</style>

<script language="JavaScript">
    document.title = "404 :: Shibata Supermercados";
    document.getElementById("page-top").removeAttribute('class');
</script>

<div id="notfound">
    <div class="notfound">
        <div class="notfound-404">
            <h3>Oops! Página Não Encontrada</h3>
            <h1><span>4</span><span>0</span><span>4</span></h1>
        </div>
        <h2>Lamentamos, mas a página solicitada não foi encontrada</h2>
        <a href="\">Voltar</a>
    </div>
</div>

